### ISSUE TITLE
some problem

### ISSUE THREAD

**Issue by conancheng** [PRBonn/range-mcl#2]
![image](https://user-images.githubusercontent.com/24214834/123219914-fc535200-d4ff-11eb-9f11-4f1f2e76cd7f.png)

XXX@ubuntu:~/range-mcl/src$ python3 main_range_mcl.py
INFO - 2021-06-24 00:21:08,437 - acceleratesupport - OpenGL_accelerate module loaded
INFO - 2021-06-24 00:21:08,451 - arraydatatype - Using accelerated ArrayDatatype
Load mesh map and initialize map module...
lower bound: [-137.51303435084705, -53.88607274849302] upper bound: [170.8931181474161, 237.73366404891496]
number of tiles =  8
total number of triangles:  4282269
WARNING - 2021-06-24 00:21:21,473 - numpymodule - Unable to load numpy_formathandler accelerator from OpenGL_accelerate
Monte Carlo localization initializing...
段错误 (核心已转储)

**Comment by Chen-Xieyuanli** [comment]
Hey @conancheng, this seems a problem with OpenGL. 

To use our code, you need a GPU. Currently, we only tested on Nvidia GPUs.

**Comment by conancheng** [comment]
> Hey @conancheng, this seems a problem with OpenGL.
> 
> To use our code, you need a GPU. Currently, we only tested on Nvidia GPUs.

Thank you!
